### ISSUE TITLE
brew install --build-from-source doesn't build from source

### ISSUE THREAD

**Issue by theorbtwo** [jakehilborn/displayplacer#108]
Hello.  Hopefully a quick one, and it's completely possible that it's my fault somehow -- I'm a reasonably experienced linux sysadmin and programmer, but very new to macos and brew.  In fact, this is the first brew I'm installing.

`brew install`, even with `--build-from-source`, doesn't actually compile, because there's a `displayplacer` binary in `displayplacer-1.2.0.tar.gz` already, and it has a newer date than the source, so `make` assumes it's already been built.  However, it fails with `bad CPU type in executable`, because it's a `x86_64` binary, rather than an `arm64` one, and I'm on an M1 mac.

I would suggest either making the executable a fat binary, or removing it from the archive.

**Comment by jakehilborn** [comment]
This issue _should_ be fixed with [release v1.3.0](https://github.com/jakehilborn/displayplacer/releases). The v.1.3.0 tar.gz that is pulled by homebrew no longer contains a prebuilt x86_64 binary.

**Comment by gingerbeardman** [comment]
Seemed broken, perhaps in a different way, but worked after I did a `brew update`.
