### ISSUE TITLE
shorter homebrew install command

### ISSUE THREAD

**Issue by navtoj** [jakehilborn/displayplacer#129]
https://github.com/jakehilborn/displayplacer/blob/248759baed08f39ad14695280e878cee4d1ec271/README.md?plain=1#L9

```bash
brew tap jakehilborn/jakehilborn && brew install displayplacer
```

The [install command](https://github.com/jakehilborn/displayplacer/blob/248759baed08f39ad14695280e878cee4d1ec271/README.md?plain=1#L9C28-L9C90) shown above can be replaced with the shorter version below for ease of typing.

```bash
brew install jakehilborn/jakehilborn/displayplacer
```

**Comment by jakehilborn** [comment]
Thanks! I incorporated this in https://github.com/jakehilborn/displayplacer/commit/37675a11595c2b726d0095f395de8f55aaea8c4f

**Comment by jakehilborn** [comment]
- [ ]
