### ISSUE TITLE
unable to run script in Automator

### ISSUE THREAD

**Issue by bremere** [jakehilborn/displayplacer#13]
I can run a script that was generated just fine within the terminal window, and it works great! I'm trying to run the script in automator and always generates an error. 

The script is:
displayplacer "id:4FA1B805-30CE-5C25-29B6-D8D149F68FEC res:1920x1200 color_depth:8 scaling:off origin:(0,0) degree:0" "id:54EF03AE-1045-6AAE-C0BD-AC5CACC7C273 res:1920x1200 color_depth:8 scaling:off origin:(1920,0) degree:0"

and the error in automator is:

"displayplacer: command not found"

What am I missing? seems pretty straight forward and I just can't get it to work :(

**Comment by jakehilborn** [comment]
Try putting the full path to the executable. Use `which` to find that path. For example

```
~ $ which displayplacer
/usr/local/bin/displayplacer
~ $ /usr/local/bin/displayplacer "id:4FA1B805-30CE-5C25-29B6-D8D149F68FEC res:1920x1200 color_depth:8 scaling:off origin:(0,0) degree:0" "id:54EF03AE-1045-6AAE-C0BD-AC5CACC7C273 res:1920x1200 color_depth:8 scaling:off origin:(1920,0) degree:0"
```

**Comment by jordanjennings** [comment]
If you have installed an updated version of bash with homebrew and set it to your default shell (as I have), then Automator tries to use it by default but it doesn't seem to work. I had to manually change the Shell dropdown in Run Shell Script to /bin/bash and use the full path to displayplacer, and now it's working.

Not working:
![image](https://user-images.githubusercontent.com/1031913/66575339-c0b60000-eb43-11e9-813b-096d26a6b56b.png)

Working:
![image](https://user-images.githubusercontent.com/1031913/66575374-cf9cb280-eb43-11e9-8ea7-1a6ce5ccd002.png)

**Comment by bremere** [comment]
Thank you both! I was able to get Automator to behave, you've both been great help!

**Comment by re-evgeny** [comment]
Thank you guys, exactly what I was looking for!

**Comment by leongeyer** [comment]
Hi. If somebody has the inverse problem, where Automator points to /bin/bash, but display placer is on /usr/local/bin/ which does not appear in the dropdown menu, insert 
`export PATH=/usr/local/bin:$PATH` at the beginning of the script. 
OS10.14.6

**Comment by kastuin** [comment]
Thanks for this I was getting very frustrated with automator ;) @jordanjennings

**Comment by Grimwoooo** [comment]
Excellent! This solved my same problem. Thank you Jake! I love Displayplacer so much!!

**Comment by FloWi** [comment]
@jordanjennings Thanks for the info regarding the path. Automator was driving me crazy :)

**Comment by JamIsJam88** [comment]
Sorry, I'm new to Automator and recently installed Homebrew just for this. Can I create this as a Quick Action and assign it to a hotkey as a service shortcut? If so, the following code is not working in a Shell Script where the shell is `/bin/bash`:

`/usr/local/bin/displayplacer "id:FAEBDFC2-38F5-4C8E-8F51-14139CA13140 res:1920x1080 hz:144 color_depth:8 scaling:off origin:(0,0) degree:0" "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1512x982 hz:120 color_depth:8 scaling:off origin:(-1512,0) degree:0" "id:8309CC09-D4BD-4FC8-BCC1-4EE98CF9F500 res:1920x1080 hz:60 color_depth:7 scaling:off origin:(0,-1080) degree:0"`

I get the error No such file or directory.

**Comment by leongeyer** [comment]
Try to write this: 
export PATH=/usr/local/bin:$PATH
displayplacer etc

 rest the same:
workflow receives no input in any app
/bin/bash pass input to stdin

**Comment by Zuxaw** [comment]
Hi if it doesn't work with all the above solutions you can do :
`brew info  displayplacer`

![image](https://user-images.githubusercontent.com/82362374/151456947-88819906-3305-44b9-a9ad-9378eebef230.png)
You will get your current displayplacer location

Then you can put in your automator : 
`/opt/homebrew/Cellar/displayplacer/1.2.0/bin/displayplacer`

![image](https://user-images.githubusercontent.com/82362374/151457167-fd97614e-1be4-4fa5-a1d9-f0cede22e960.png)

**Comment by JamIsJam88** [comment]
> Hi if it doesn't work with all the above solutions you can do : `brew info displayplacer`
> 
> ![image](https://user-images.githubusercontent.com/82362374/151456947-88819906-3305-44b9-a9ad-9378eebef230.png) You will get your current displayplacer location
> 
> Then you can put in your automator : `/opt/homebrew/Cellar/displayplacer/1.2.0/bin/displayplacer`
> 
> ![image](https://user-images.githubusercontent.com/82362374/151457167-fd97614e-1be4-4fa5-a1d9-f0cede22e960.png)

This worked perfectly. Thanks so much!
