### ISSUE TITLE
Avoid broken screen

### ISSUE THREAD

**Issue by marekmaurizio** [jakehilborn/displayplacer#15]
Hello, can I use this to avoid a portion of broken screen on the right side?

**Comment by jakehilborn** [comment]
You may have some luck with `displayplacer` providing a resolution that uses a letterboxed aspect ratio that avoids the broken section of your screen. Something like this: 

![](https://docs.coronalabs.com/images/simulator/content-letterbox.png)

I recommend downloading SwitchResX and using the 10 day trial to find out if you can create a custom resolution that somehow avoids your specific broken section.
