### ISSUE TITLE
Configure a similar command line API to xrandr

### ISSUE THREAD

**Issue by Ryan-Gordon** [jakehilborn/displayplacer#2]
As a displayplacer user 
I would like a way to use displayplacer just like I would use xrandr
so that I have access to a similar command pallet as xrandr itself. 

An example : 
displayplacer --output <name_of_output_socket> --mode <resolution> --pos <position>  --rotate <rotate left or right>

This might require making an issue for each command

**Comment by jakehilborn** [comment]
Hey Ryan,

I do not have plans to mimic the interface of xrandr. Though the command line options are different, I interact with them infrequently since I invoke displayplacer through scripts.
