### ISSUE TITLE
Killed: 9 when running displayplacer

### ISSUE THREAD

**Issue by hrv-sp** [jakehilborn/displayplacer#29]
I just installed via homebrew and any command I perform ends up with the same result.

./displayplacer list
Killed: 9
./displayplacer --version
Killed: 9

pwd
/usr/local/Cellar/displayplacer/1.2.0/bin

Unfortunately, I am no programmer, I have no clue how to troubleshoot. I couldn't locate any log file that could tell me what is going on.

I am running High-Sierra, macOS 10.13.6

**Comment by jakehilborn** [comment]
Can you check if displayplacer is on your path? Execute `which displayplacer`, hopefully it outputs `/usr/local/bin/displayplacer`.

If so, you should be able to run displayplacer from any directory and omit the `./` so you simply execute `displayplacer list`. Note, some keyboard shortcut programs will need you to put the full path so instead you would do `/usr/local/bin/displayplacer list`.

**Comment by hrv-sp** [comment]
Hi Jake, thanks for coming back to me.

It does run from anywhere and which provides the correct path.
Still the message returned is Killed: 9
According to Google on a Mac it means some dependency may be missing. The program is unresponsive and getting killed by the system.

**Comment by hrv-sp** [comment]
Good news, I upgraded from High Sierra to Catalina and I can now run the program :-)
