### ISSUE TITLE
Shortcut automation error

### ISSUE THREAD

**Issue by tonewarper** [jakehilborn/displayplacer#37]
I know this is arguably an Automation not Displayplacer issue, but I’m one of probably dozens of non-developer casual Mac users who’ve been referred to this great tool from forums in search of a fix for screen rotation setting remembrance, and struggled thereafter to find on the net any helpful resource to get it to work (I also checked the readme file here, maybe I missed something?). An answer here or beefing up documentation just a bit would be appreciated by many, thanks! 

I’ve successfully installed and ran displayplacer to get the script for my display. Following various forum how-to’s, I created in Automator a Quick Action (Service) profile and saved it, containing the following (using AppleScript type, and workflow set to No input from any application): 

```
on run {input, parameters}
	
	(displayplacer "id:933C106C-08BC-09AA-F750-C2A74A119DEF res:1440x900 color_depth:4 scaling:off origin:(0,0) degree:0" "id:6007C6A1-FAFB-AA24-6E9A-3B50F41C0EFC res:1080x1920 hz:60 color_depth:4 scaling:off origin:(214,-1920) degree:90")
	
	return input
end run
```

I then created a shortcut in Keyboard settings for the saved script file. Then, per further forums advice, I went to Security settings for Accessibility and added Automator, and Finder, and Displayplacer… then proceeded to put my Mac to sleep and back on… expectedly, the rotation settings had been forgotten. So I excitedly entered my keyboard shortcut… but then got the following popup window: 

**_The action “Run AppleScript” encountered an error: “The operation couldn’t be completed. (com.apple.Automator error -212.)”_**

Help please! Thank you!

**Comment by jakehilborn** [comment]
Check if anything in this thread helps. I use BetterTouchTool instead of Automator, but if you're still having issues I can experiment with Automator to get yours working. https://github.com/jakehilborn/displayplacer/issues/13

**Comment by tonewarper** [comment]
Thanks Jake! Still having teething issues… per comments on the other thread you linked to, I replaced my Automator script workflow file text with:
```
export PATH=/usr/local/bin:$PATH
on run {input, parameters}	
	(/usr/local/bin/displayplacer "id:933C106C-08BC-09AA-F750-C2A74A119DEF res:1440x900 color_depth:4 scaling:off origin:(0,0) degree:0" "id:6007C6A1-FAFB-AA24-6E9A-3B50F41C0EFC res:1080x1920 hz:60 color_depth:4 scaling:off origin:(214,-1920) degree:90”)
	return input
end run
```
Same error result when I input the keyboard shortcut sequence. I took a look at BetterTouchTool, but since it’s paid, I thought a fix with MacOS’s built-in services would be accessible to more people beyond the trial period. 

Ah the things one has to go through to undo Apple shenanigans to sell you their own accessories instead of using 3rd party ones...

**Comment by andrewdbond** [comment]
@tonewarper -

As you say, this is an Automator item, not a displayplacer item. However...

Ignoring the keyboard side of things for the moment, does your Quick Action do what you want it to when you click Run inside of Automator? Should get that working first.

I believe your Quick Action should have one action within it: "Run Shell Script".
You can then set the text within that action to be:

```
/usr/local/bin/displayplacer "id:933C106C-08BC-09AA-F750-C2A74A119DEF res:1440x900 color_depth:4 scaling:off origin:(0,0) degree:0" "id:6007C6A1-FAFB-AA24-6E9A-3B50F41C0EFC res:1080x1920 hz:60 color_depth:4 scaling:off origin:(214,-1920) degree:90”
```

If it's the keyboard side of things that you're getting stuck on, an alternative approach to a MacOS keyboard shortcut is the free https://github.com/deseven/icanhazshortcut - use the code line I provided immediately above as the command within it.

If you're still having trouble, it may be helpful if you could provide screenshot(s) and possibly links to the forum how-to(s) that you based your approach on, thanks.

**Comment by tonewarper** [comment]
Almost there!! YES, most of the problems were because I had created an AppleScript instead of Shell action, something the forum solutions overlooked spelling out. I still had some syntax problems from the " being reformed into a “ which I spotted and debugged. The script now performs the desired action and rotates my screen properly 90’ when run, but there’s something not quite right that makes it additionally display an error pop-up every time I run the workflow within Automator or the keyboard-shortcut I mapped to it. 

![Screen Shot 2020-06-27 at 6 20 36 PM](https://user-images.githubusercontent.com/46685787/85924583-577a4680-b8a4-11ea-9c57-08ac36cb0d58.png)

I tried removing that snippet in question (_res:1080x1920 hz:60 color_depth:4 scaling:on_) but it repeats the same error just the resolution numbers in the error notice become 0x0. I’m having trouble digging out the Apple Communities and Stackoverflow threads that led me here and talked about Automator scripts after a rudimentary history search, but I can do another googling to find them again if necessary.

I think we’ve entered Displayplacer syntax not automator issues now?

**Comment by andrewdbond** [comment]
To confirm, when you attempt to run that whole command in Terminal (instead of in Automator), does it work? If not:

1. Configure / rotate your screens as you want them.
2. From Terminal, run `displayplacer list`
3. See the very last line(s) of output for the command that you should use. Compare it to what you have been using.

Alternatively, you may be able to remove the pieces from your command that you don't need the script to change. For example, you may want to only try including the `id` and `degree` fields. You might also only need to configure one screen, not both.

**Comment by tonewarper** [comment]
Thank you , these suggestions worked! Stay safe all
