### ISSUE TITLE
This is a great tool!

### ISSUE THREAD

**Issue by enjay314** [jakehilborn/displayplacer#4]
This is probably a rookie Github move but you've made a great bit of code here and I wanted to thank you! 

I have my monitors on moveable armatures so am often rearranging which screen is to the left/right, above/below the other and this will make it much easier to quickly update their arrangement. This is exactly what I need. Course it'd be nice if I could just run it from the menubar or something but I'll find a script or app to let me do that next ;)

Safari adds ".dms" to the executable download for some reason so once I downloaded the folder of files instead, I got it working. It was only later that I realized I could strip the ".dms" from the file, run chmod to make it executable, and then use the original executable.

Anyway, excited to make a couple shortcuts for this; it's working great from Terminal and will come in handy. Thanks very much!

**Comment by jakehilborn** [comment]
Thank you for the kind words!

I need to push the current dev version to a new release so that the latest downloadable .zip has the newest features. This should get around the extensionless file download issue. Good to know about Safari's file extension trickery.

**Comment by jakehilborn** [comment]
Installation is now supported through Homebrew. `brew tap jakehilborn/jakehilborn && brew install displayplacer`

**Comment by ffffwh** [comment]
Thank you @ jakehilborn for the handy tool.

My usage is to set `color_depth:4` (8-bit color mode), since most 10-bit consumer-level monitor is actually 8-bit + FRC. FRC might cause slightly flickering.

Leaving some keywords for anyone with the same purpose.
- macOS disable 10-bit / 30-bit color depth / framebuffer depth
- macOS set 8-bit / 24-bit color depth
