### ISSUE TITLE
Unable to install displayplacer via Homebrew

### ISSUE THREAD

**Issue by HelloPuppet** [jakehilborn/displayplacer#46]
`brew install displayplacer` returns the following error:

Error: The following formula
  displayplacer
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

**Comment by HelloPuppet** [comment]
Just wanted to update that I think I've got it figured out.

XCode is out of date as well as the developer tools.
Anyone else having this issue should run `brew doctor` and it likely will tell you exactly what's wrong and how to fix it.

**Comment by timsully** [comment]
Just following up, your issue has been resolved, correct? If so, awesome!!!

**Comment by HelloPuppet** [comment]
> @HelloPuppet Just following up, your issue has been resolved, correct? If so, awesome!!!

It has @timsully!  Thanks for checking in I'll mark this resolved.

Just and to install and update Xcode/Dev tools and then correct a few things within homebrew using `brew doctor`
