### ISSUE TITLE
Does this run on Big Sur?

### ISSUE THREAD

**Issue by Trisky** [jakehilborn/displayplacer#51]
I'm planning to update to Big Sur but I really use this tool every day since MacOS keeps forgetting my 3 screen placement settings almost every time I unplug my computer from the monitors.

Has anybody tested it?

**Comment by Uupis** [comment]
I've had no issues in the 5 days I've been using Big Sur. Just re-ran my script to be sure, and everything seems fine.

Tangentially, I seem to have much better luck with Big Sur remembering my display arrangement in general.

**Comment by Trisky** [comment]
Thanks for confirming!

I updated to Big Sur and it works like a charm. 🎉 
 I just had to use it because MacOS forgot the position of my screens again 😓 .
