### ISSUE TITLE
Can you use this utility for turning on / off mirroring?

### ISSUE THREAD

**Issue by AdamBD** [jakehilborn/displayplacer#58]
Hi,

I am looking to programmatically control mirroring but didnt see anything related to that in the README.

Is there a way to control mirroring with this utility?

**Comment by billylo1** [comment]
macOS has a built-in shortcut. Command-F1 will toggle mirroring. Hope this helps.

**Comment by AdamBD** [comment]
@billylo1 WHOA! Mind blown. Thanks so much!
