### ISSUE TITLE
Get "error finalizing display configurations" error

### ISSUE THREAD

**Issue by fluffy-critter** [jakehilborn/displayplacer#59]
I'm running macOS 11.2 on an M1 Mac mini with an LG 4K HDR monitor, and whether I run the homebrew release or build from source, most commands I run give me an error without applying any changes. For example, if I use the configuration restoring command from `displayplacer list`, this happens:

```
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 res:2560x1440 hz:60 color_depth:8 scaling:on origin:(0,0) degree:0" "id:1D8AB08D-7B12-48C9-0857-D6964E3302DB res:1920x1080 hz:60 color_depth:8 scaling:off origin:(2560,-60) degree:0"

Error finalizing display configurations
```
If I set just the resolution, it works fine, though; these commands work without error:

```
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 res:3840x2160" 
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 res:2560x1440"
```

If I add `color_depth` back in, the error comes back:

```
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 res:2560x1440 color_depth:8"
Error finalizing display configurations
```

Specifying resolutions by mode number works as well:

```
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 mode:155"                   
bucket:~ $ displayplacer "id:98AD201D-167F-2937-3D19-FC1626C9B248 mode:130"
```

Since I'm on an HDR monitor I suspect there's something wrong with how it's trying to set the color depth.

**Comment by fluffy-critter** [comment]
Never mind, turns out that it just shows that error if there's no changes to apply.

**Comment by frranck** [comment]
well you shouldn't close this, that's a valid bug.

**Comment by AB1908** [comment]
Perhaps we can add this to the readme so newbies ilke me aren't confused.
