### ISSUE TITLE
displayplacer list is not working

### ISSUE THREAD

**Issue by kmanpdx** [jakehilborn/displayplacer#64]
I'm installing on Mac Catalina hosted in amazon.  On a couple EC2 instances it worked.  On the others, it does not.  I get this:

             .:'
         __ :'__       __|  __|_  )
      .'`  `-'  ``.    _|  (     /
     :          .-'   ___|\___|___|
     :         :
      :         `-;   Amazon EC2
       `.__.-.__.'    macOS Catalina 10.15.7

ec2-user@tcs-sing-mac3-az1a ~ % displayplacer list
Execute the command below to set your screens to the current arrangement:

displayplacer

And if I just run displayplacer by itself I get the help list.  I tried running sudo also.  Any pointers?  All the mac instances were configured exactly the same

**Comment by kmanpdx** [comment]
OK nevermind!  I built the Mac from AWS console and SSH'd into it.  I had not started VNC / ARD remote access to it, so there was no display yet.  

Would be useful if your app handled that case and let the end user know they have issues :). thanks

**Comment by HarryWeppner** [comment]
@kmanpdx ran into this, too. However, it appears that you not only have to [start the ARD agent](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-mac-instances.html#mac-screen-resolution) but you need to also have a connection established before a (virtual) display is created. Have you by chance dealt with the situation of using `displayplacer` in a CI/CD context _without_ an active VNC/ARD connection?
