### ISSUE TITLE
No effect and no erros after running 'displayplacer "id:..." '

### ISSUE THREAD

**Issue by mac137** [jakehilborn/displayplacer#79]
Hi! macOS Monterey 12.1, MBP 14" with M1 Pro, with 2 external monitors connected to the laptop via StarTech dock

I arranged my screens, ran `displayplacer list` and saved the command
```
displayplacer "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1512x982 hz:120 color_depth:8 scaling:on origin:(0,0) degree:0" "id:F09AC03D-52A7-4496-8895-173B224CBD2A res:2560x1440 hz:120 color_depth:8 scaling:off origin:(759,-1440) degree:0" "id:241C331E-597B-4153-A1BC-3570D60FD570 res:2560x1440 hz:120 color_depth:8 scaling:off origin:(-1801,-1440) degree:0"
```

rearranged my screens and ran the above command with no effect and no errors.

Also the same outcome after running the command with `sudo`

Any idea how to make the command work?

**Comment by maciej-3** [comment]
Actually, there is an effect, and the command works! The problem is that the opening applications stay in the "old" (wrong) positions after running the command.
