### ISSUE TITLE
Set a custom resolution?

### ISSUE THREAD

**Issue by OlleLinderos** [jakehilborn/displayplacer#8]
First of all, this seems awesome. Always wanted xrandr for Mac :) 

My issue is that my laptop screen is broken and I have a centimeter of dead pixels along the whole right side of my screen. So what I'm looking to achieve is to set a custom resolution that will exclude that part of the screen. In xrandr this could be done by creating a new mode I think. Is this possible? Thank you!

**Comment by jakehilborn** [comment]
displayplacer does not support creating custom resolutions. It's functionality is to switch between existing resolutions.

You can follow guides like this to create custom resolutions. Alternatively, you can use SwitchResX for an easy GUI that does the same thing as shown in the links below.

https://www.insanelymac.com/forum/topic/290097-guide-108-add-your-custom-retina-hidpi-resolution-for-your-desktop-display/
https://www.tonymacx86.com/threads/adding-using-hidpi-custom-resolutions.133254/

**Comment by OlleLinderos** [comment]
Thank you so much!
