### ISSUE TITLE
Use USB-C/HDMI port ID instead of persistent/contextual ID

### ISSUE THREAD

**Issue by angel-langdon** [jakehilborn/displayplacer#83]
I have 3 monitors that are the same model (Samsung M5 32")

I have tried both persistent and contextual IDs but the IDs keep switching and my scripts are not longer valid

I could create 6 scripts with all the possible permutations and try each one but I think that is not a very good solution

Is there a way to use USB-C/HDMI port ID instead of persistent/contextual IDs?

**Comment by r14n** [comment]
I also found that the ID seems to change (I think the very long one is meant to be the persistent).  I just always want my scripts to reference my external monitor, how should I do that?  I use my macbook air mostly closed hooked up to an external.

**Comment by darrenaalfonso** [comment]
Same issue.  Script doesn't work because somehow the IDs are getting switched.

**Comment by jakehilborn** [comment]
@angel-langdon @r14n @darrenaalfonso displayplacer [v1.4.0](https://github.com/jakehilborn/displayplacer/releases) supports addressing screens by serial id. If all of the screens in your setup have unique serial ids, this should fix the id switching issue.

Could you try out the new version and let me know if it works on your setup?
