### ISSUE TITLE
how to swap the position of the 2 external screens?

### ISSUE THREAD

**Issue by PatrickRoumanoff** [jakehilborn/displayplacer#9]
I work in an office where all desks have 2 screens but the docking station is setup so that either left port is on right or left port is on left, everytime I have to adjust the position of the external screens.
I tried to use `displayplacer list` but the id is changing with every docking station / monitor.

So really what I want is the ability to swap around the position of  monitor 1 and monitor 2.

Should I go with a shell script or would it make a valuable feature for the tool?

**Comment by jakehilborn** [comment]
It sounds like the monitors and/or docking stations have slight differences causing the ids to change. Be sure to check if perhaps the contextual screen id or persistent screen id is staying the same.

If the ids do not stay the same, then yes your best bet is to write a shell script to swap the position of the two displays. A shell script that executes `displayplacer list`, swaps the x coordinate of both displays, and then runs displayplacer to set the layout should do the trick.
